version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Montar el directorio actual en el contenedor para facilitar el desarrollo
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password_root
      MYSQL_DATABASE: erney
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    volumes:
      - ./data_mysql:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
